name: splainer

type: node

up:
  - node:
      yarn: true
      version: v16.14.2
  - railgun

commands:
  server:
    run: node app/index.js

env:
  ELASTICSEARCH_URL: "http://splainer.railgun:9200"

open:
  app: "https://splainer.myshopify.io"

